import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>swap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{width: '100%'}}>
        <h1>swap-page</h1>
        <Image src="/jt.png" width="1000px" height="600px" />
        <pre>
          <code>
          {
            `
              [
                {
                  name: 'react',
                  entry: '//localhost:9001',
                  container: '#root',
                  activeRule: '/react',
                }
              ]
            `
          }
          </code>
        </pre>
      </main>
    </div>
  )
}

export default Home
